package rfc.entity;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Administrator on 2017/7/22.
 */
public class  HandicapDataEntity {

    public static List<HandicapEntity> globalHandicap = new ArrayList<HandicapEntity>();

    static {

        HandicapEntity he1 = new HandicapEntity("平手",0);
        HandicapEntity he2 = new HandicapEntity("受平手",0);
        HandicapEntity he3 = new HandicapEntity("平/半",-25);
        HandicapEntity he4 = new HandicapEntity("受平/半",25);
        HandicapEntity he5 = new HandicapEntity("半球",-50);
        HandicapEntity he6 = new HandicapEntity("受半球",50);
        HandicapEntity he7 = new HandicapEntity("半/一",-75);
        HandicapEntity he8 = new HandicapEntity("受半/一",75);
        HandicapEntity he9 = new HandicapEntity("一球",-100);
        HandicapEntity he10 = new HandicapEntity("受一球",100);
        HandicapEntity he11 = new HandicapEntity("一/球半",-125);
        HandicapEntity he12 = new HandicapEntity("受一/球半",125);
        HandicapEntity he13 = new HandicapEntity("球半",-150);
        HandicapEntity he14 = new HandicapEntity("受球半",150);
        HandicapEntity he15 = new HandicapEntity("球半/两",-175);
        HandicapEntity he16 = new HandicapEntity("受球半/两",175);
        HandicapEntity he17 = new HandicapEntity("两球",-200);
        HandicapEntity he18 = new HandicapEntity("受两球",200);
        HandicapEntity he19 = new HandicapEntity("两/两球半",-225);
        HandicapEntity he20 = new HandicapEntity("受两/两球半",225);
        HandicapEntity he21 = new HandicapEntity("两球半",-250);
        HandicapEntity he22 = new HandicapEntity("受两球半",250);
        HandicapEntity he23 = new HandicapEntity("两球半/三",-275);
        HandicapEntity he24 = new HandicapEntity("受两球半/三",275);
        HandicapEntity he25 = new HandicapEntity("三球",-300);
        HandicapEntity he26 = new HandicapEntity("受三球",300);
        HandicapEntity he27 = new HandicapEntity("三/三球半",-325);
        HandicapEntity he28 = new HandicapEntity("受三/三球半",325);
        HandicapEntity he29 = new HandicapEntity("三球半",-350);
        HandicapEntity he30 = new HandicapEntity("受三球半",350);
        HandicapEntity he31 = new HandicapEntity("三球半/四",-375);
        HandicapEntity he32 = new HandicapEntity("受三球半/四",375);
        HandicapEntity he33 = new HandicapEntity("四球",-400);
        HandicapEntity he34 = new HandicapEntity("受四球",400);
        HandicapEntity he35 = new HandicapEntity("四/四球半",-425);
        HandicapEntity he36 = new HandicapEntity("受四/四球半",425);
        HandicapEntity he37 = new HandicapEntity("四球半",-450);
        HandicapEntity he38 = new HandicapEntity("受四球半",450);
        HandicapEntity he39 = new HandicapEntity("四球半/五",-475);
        HandicapEntity he40 = new HandicapEntity("受四球半/五",475);
        HandicapEntity he41 = new HandicapEntity("五球",-500);
        HandicapEntity he42 = new HandicapEntity("受五球",500);
        HandicapEntity he43 = new HandicapEntity("五/五球半",-525);
        HandicapEntity he44 = new HandicapEntity("受五/五球半",525);
        HandicapEntity he45 = new HandicapEntity("五球半",-550);
        HandicapEntity he46 = new HandicapEntity("受五球半",550);
        HandicapEntity he47 = new HandicapEntity("五球半/六",-575);
        HandicapEntity he48 = new HandicapEntity("受五球半/六",575);
        HandicapEntity he49 = new HandicapEntity("六球",-600);
        HandicapEntity he50 = new HandicapEntity("受六球",600);
        HandicapEntity he51 = new HandicapEntity("六/六球半",-625);
        HandicapEntity he52 = new HandicapEntity("受六/六球半",625);
        HandicapEntity he53 = new HandicapEntity("六球半",-650);
        HandicapEntity he54 = new HandicapEntity("受六球半",650);
        HandicapEntity he55 = new HandicapEntity("六球半/七",-675);
        HandicapEntity he56 = new HandicapEntity("受六球半/七",675);
        HandicapEntity he57 = new HandicapEntity("七球",-700);
        HandicapEntity he58 = new HandicapEntity("受七球",700);
        HandicapEntity he59 = new HandicapEntity("七/七球半",-725);
        HandicapEntity he60 = new HandicapEntity("受七/七球半",725);
        HandicapEntity he61 = new HandicapEntity("七球半",-750);
        HandicapEntity he62 = new HandicapEntity("受七球半",750);
        HandicapEntity he63 = new HandicapEntity("七球半/八",-775);
        HandicapEntity he64 = new HandicapEntity("受七球半/八",775);
        HandicapEntity he65 = new HandicapEntity("八球",-800);
        HandicapEntity he66 = new HandicapEntity("受八球",800);
        HandicapEntity he67 = new HandicapEntity("八/八球半",-825);
        HandicapEntity he68 = new HandicapEntity("受八/八球半",825);
        HandicapEntity he69 = new HandicapEntity("八球半",-850);
        HandicapEntity he70 = new HandicapEntity("受八球半",850);
        HandicapEntity he71 = new HandicapEntity("八球半/九",-875);
        HandicapEntity he72 = new HandicapEntity("受八球半/九",875);
        HandicapEntity he73 = new HandicapEntity("九球",-900);
        HandicapEntity he74 = new HandicapEntity("受九球",900);
        HandicapEntity he75 = new HandicapEntity("九/九球半",-925);
        HandicapEntity he76 = new HandicapEntity("受九/九球半",925);
        HandicapEntity he77 = new HandicapEntity("九球半",-950);
        HandicapEntity he78 = new HandicapEntity("受九球半",950);
        HandicapEntity he79 = new HandicapEntity("九球半/十",-975);
        HandicapEntity he80 = new HandicapEntity("受九球半/十",975);
        HandicapEntity he81 = new HandicapEntity("十球",-1000);
        HandicapEntity he82 = new HandicapEntity("受十球",1000);
        HandicapEntity he83 = new HandicapEntity("十/十球半",-1025);
        HandicapEntity he84 = new HandicapEntity("受十/十球半",1025);
        HandicapEntity he85 = new HandicapEntity("十球半",-1050);
        HandicapEntity he86 = new HandicapEntity("受十球半",1050);
        HandicapEntity he87 = new HandicapEntity("十球半/十一",-1075);
        HandicapEntity he88 = new HandicapEntity("受十球半/十一",1075);
        HandicapEntity he89 = new HandicapEntity("十一球",-1100);
        HandicapEntity he90 = new HandicapEntity("受十一球",1100);
        HandicapEntity he91 = new HandicapEntity("十一/十一球半",-1125);
        HandicapEntity he92 = new HandicapEntity("受十一/十一球半",1125);
        HandicapEntity he93 = new HandicapEntity("十一球半",-1150);
        HandicapEntity he94 = new HandicapEntity("受十一球半",1150);
        HandicapEntity he95 = new HandicapEntity("十一球半/十二",-1175);
        HandicapEntity he96 = new HandicapEntity("受十一球半/十二",1175);
        HandicapEntity he97 = new HandicapEntity("十二球",-1200);
        HandicapEntity he98 = new HandicapEntity("受十二球",1200);
        HandicapEntity he99 = new HandicapEntity("十二/十二球半",-1225);
        HandicapEntity he100 = new HandicapEntity("受十二/十二球半",1225);
        HandicapEntity he101 = new HandicapEntity("十二球半",-1250);
        HandicapEntity he102 = new HandicapEntity("受十二球半",1250);
        HandicapEntity he103 = new HandicapEntity("十二球半/十三",-1275);
        HandicapEntity he104 = new HandicapEntity("受十二球半/十三",1275);
        HandicapEntity he105 = new HandicapEntity("十三球",-1300);
        HandicapEntity he106 = new HandicapEntity("受十三球",1300);
        HandicapEntity he107 = new HandicapEntity("十三/十三球半",-1325);
        HandicapEntity he108 = new HandicapEntity("受十三/十三球半",1325);
        HandicapEntity he109 = new HandicapEntity("十三球半",-1350);
        HandicapEntity he110 = new HandicapEntity("受十三球半",1350);
        HandicapEntity he111 = new HandicapEntity("十三球半/十四",-1375);
        HandicapEntity he112 = new HandicapEntity("受十三球半/十四",1375);
        HandicapEntity he113 = new HandicapEntity("十四球",-1400);
        HandicapEntity he114 = new HandicapEntity("受十四球",1400);
        HandicapEntity he115 = new HandicapEntity("十四/十四球半",-1425);
        HandicapEntity he116 = new HandicapEntity("受十四/十四球半",1425);
        HandicapEntity he117 = new HandicapEntity("十四球半",-1450);
        HandicapEntity he118 = new HandicapEntity("受十四球半",1450);
        HandicapEntity he119 = new HandicapEntity("十四球半/十五",-1475);
        HandicapEntity he120 = new HandicapEntity("受十四球半/十五",1475);
        HandicapEntity he121 = new HandicapEntity("十五球",-1500);
        HandicapEntity he122 = new HandicapEntity("受十五球",1500);
        HandicapEntity he123 = new HandicapEntity("十五/十五球半",-1525);
        HandicapEntity he124 = new HandicapEntity("受十五/十五球半",1525);
        HandicapEntity he125 = new HandicapEntity("十五球半",-1550);
        HandicapEntity he126 = new HandicapEntity("受十五球半",1550);
        HandicapEntity he127 = new HandicapEntity("十五球半/十六",-1575);
        HandicapEntity he128 = new HandicapEntity("受十五球半/十六",1575);
        HandicapEntity he129 = new HandicapEntity("十六球",-1600);
        HandicapEntity he130 = new HandicapEntity("受十六球",1600);
        HandicapEntity he131 = new HandicapEntity("十六/十六球半",-1625);
        HandicapEntity he132 = new HandicapEntity("受十六/十六球半",1625);
        HandicapEntity he133 = new HandicapEntity("十六球半",-1650);
        HandicapEntity he134 = new HandicapEntity("受十六球半",1650);
        HandicapEntity he135 = new HandicapEntity("十六球半/十七",-1675);
        HandicapEntity he136 = new HandicapEntity("受十六球半/十七",1675);
        HandicapEntity he137 = new HandicapEntity("十七球",-1700);
        HandicapEntity he138 = new HandicapEntity("受十七球",1700);
        HandicapEntity he139 = new HandicapEntity("十七/十七球半",-1725);
        HandicapEntity he140 = new HandicapEntity("受十七/十七球半",1725);
        HandicapEntity he141 = new HandicapEntity("十七球半",-1750);
        HandicapEntity he142 = new HandicapEntity("受十七球半",1750);
        HandicapEntity he143 = new HandicapEntity("十七球半/十八",-1775);
        HandicapEntity he144 = new HandicapEntity("受十七球半/十八",1775);
        HandicapEntity he145 = new HandicapEntity("十八球",-1800);
        HandicapEntity he146 = new HandicapEntity("受十八球",1800);
        HandicapEntity he147 = new HandicapEntity("十八/十八球半",-1825);
        HandicapEntity he148 = new HandicapEntity("受十八/十八球半",1825);
        HandicapEntity he149 = new HandicapEntity("十八球半",-1850);
        HandicapEntity he150 = new HandicapEntity("受十八球半",1850);
        HandicapEntity he151 = new HandicapEntity("十八球半/十九",-1875);
        HandicapEntity he152 = new HandicapEntity("受十八球半/十九",1875);
        HandicapEntity he153 = new HandicapEntity("十九球",-1900);
        HandicapEntity he154 = new HandicapEntity("受十九球",1900);
        HandicapEntity he155 = new HandicapEntity("十九/十九球半",-1925);
        HandicapEntity he156 = new HandicapEntity("受十九/十九球半",1925);
        HandicapEntity he157 = new HandicapEntity("十九球半",-1950);
        HandicapEntity he158 = new HandicapEntity("受十九球半",1950);
        HandicapEntity he159 = new HandicapEntity("十九球半/二十",-1975);
        HandicapEntity he160 = new HandicapEntity("受十九球半/二十",1975);
        HandicapEntity he161 = new HandicapEntity("二十球",-2000);
        HandicapEntity he162 = new HandicapEntity("受二十球",2000);
        HandicapEntity he163 = new HandicapEntity("二十/二十球半",-2025);
        HandicapEntity he164 = new HandicapEntity("受二十/二十球半",2025);
        HandicapEntity he165 = new HandicapEntity("二十球半",-2050);
        HandicapEntity he166 = new HandicapEntity("受二十球半",2050);
        HandicapEntity he167 = new HandicapEntity("0",0);
        HandicapEntity he168 = new HandicapEntity("-1",-150);
        HandicapEntity he169 = new HandicapEntity("+1",150);
        HandicapEntity he170 = new HandicapEntity("-2",-250);
        HandicapEntity he171 = new HandicapEntity("+2",250);
        HandicapEntity he172 = new HandicapEntity("-3",-350);
        HandicapEntity he173 = new HandicapEntity("+3",350);
        HandicapEntity he174 = new HandicapEntity("-4",-450);
        HandicapEntity he175 = new HandicapEntity("+4",450);
        HandicapEntity he176 = new HandicapEntity("-5",-550);
        HandicapEntity he177 = new HandicapEntity("+5",550);
        HandicapEntity he178 = new HandicapEntity("-6",-650);
        HandicapEntity he179 = new HandicapEntity("+6",650);
        HandicapEntity he180 = new HandicapEntity("-7",-750);
        HandicapEntity he181 = new HandicapEntity("+7",750);
        HandicapEntity he182 = new HandicapEntity("-8",-850);
        HandicapEntity he183 = new HandicapEntity("+8",850);
        HandicapEntity he184 = new HandicapEntity("-9",-950);
        HandicapEntity he185 = new HandicapEntity("+9",950);
        HandicapEntity he186 = new HandicapEntity("-10",-1050);
        HandicapEntity he187 = new HandicapEntity("+10",1050);
        HandicapEntity he188 = new HandicapEntity("-11",-1150);
        HandicapEntity he189 = new HandicapEntity("+11",1150);
        HandicapEntity he190 = new HandicapEntity("-12",-1250);
        HandicapEntity he191 = new HandicapEntity("+12",1250);
        HandicapEntity he192 = new HandicapEntity("-13",-1350);
        HandicapEntity he193 = new HandicapEntity("+13",1350);
        HandicapEntity he194 = new HandicapEntity("-14",-1450);
        HandicapEntity he195 = new HandicapEntity("+14",1450);
        HandicapEntity he196 = new HandicapEntity("-15",-1550);
        HandicapEntity he197 = new HandicapEntity("+15",1550);
        HandicapEntity he198 = new HandicapEntity("-16",-1650);
        HandicapEntity he199 = new HandicapEntity("+16",1650);
        HandicapEntity he200 = new HandicapEntity("-17",-1750);
        HandicapEntity he201 = new HandicapEntity("+17",1750);
        HandicapEntity he202 = new HandicapEntity("-18",-1850);
        HandicapEntity he203 = new HandicapEntity("+18",1850);
        HandicapEntity he204 = new HandicapEntity("-19",-1950);
        HandicapEntity he205 = new HandicapEntity("+19",1950);
        HandicapEntity he206 = new HandicapEntity("-15",-1550);
        HandicapEntity he207 = new HandicapEntity("-20",-2050);
        HandicapEntity he208 = new HandicapEntity("+20",2050);


        globalHandicap.add(he1);
        globalHandicap.add(he2);
        globalHandicap.add(he3);
        globalHandicap.add(he3);
        globalHandicap.add(he4);
        globalHandicap.add(he5);
        globalHandicap.add(he6);
        globalHandicap.add(he7);
        globalHandicap.add(he8);
        globalHandicap.add(he9);
        globalHandicap.add(he10);
        globalHandicap.add(he11);
        globalHandicap.add(he12);
        globalHandicap.add(he13);
        globalHandicap.add(he14);
        globalHandicap.add(he15);
        globalHandicap.add(he16);
        globalHandicap.add(he17);
        globalHandicap.add(he18);
        globalHandicap.add(he19);
        globalHandicap.add(he20);
        globalHandicap.add(he21);
        globalHandicap.add(he22);
        globalHandicap.add(he23);
        globalHandicap.add(he24);
        globalHandicap.add(he25);
        globalHandicap.add(he26);
        globalHandicap.add(he27);
        globalHandicap.add(he28);
        globalHandicap.add(he29);
        globalHandicap.add(he30);
        globalHandicap.add(he31);
        globalHandicap.add(he32);
        globalHandicap.add(he33);
        globalHandicap.add(he34);
        globalHandicap.add(he35);
        globalHandicap.add(he36);
        globalHandicap.add(he37);
        globalHandicap.add(he38);
        globalHandicap.add(he39);
        globalHandicap.add(he40);
        globalHandicap.add(he41);
        globalHandicap.add(he42);
        globalHandicap.add(he43);
        globalHandicap.add(he44);
        globalHandicap.add(he45);
        globalHandicap.add(he46);
        globalHandicap.add(he47);
        globalHandicap.add(he48);
        globalHandicap.add(he49);
        globalHandicap.add(he50);
        globalHandicap.add(he51);
        globalHandicap.add(he52);
        globalHandicap.add(he53);
        globalHandicap.add(he54);
        globalHandicap.add(he55);
        globalHandicap.add(he56);
        globalHandicap.add(he57);
        globalHandicap.add(he58);
        globalHandicap.add(he59);
        globalHandicap.add(he60);
        globalHandicap.add(he61);
        globalHandicap.add(he62);
        globalHandicap.add(he63);
        globalHandicap.add(he64);
        globalHandicap.add(he65);
        globalHandicap.add(he66);
        globalHandicap.add(he67);
        globalHandicap.add(he68);
        globalHandicap.add(he69);
        globalHandicap.add(he70);
        globalHandicap.add(he71);
        globalHandicap.add(he72);
        globalHandicap.add(he73);
        globalHandicap.add(he74);
        globalHandicap.add(he75);
        globalHandicap.add(he76);
        globalHandicap.add(he77);
        globalHandicap.add(he78);
        globalHandicap.add(he79);
        globalHandicap.add(he80);
        globalHandicap.add(he81);
        globalHandicap.add(he82);
        globalHandicap.add(he83);
        globalHandicap.add(he84);
        globalHandicap.add(he85);
        globalHandicap.add(he86);
        globalHandicap.add(he87);
        globalHandicap.add(he88);
        globalHandicap.add(he89);
        globalHandicap.add(he90);
        globalHandicap.add(he91);
        globalHandicap.add(he92);
        globalHandicap.add(he93);
        globalHandicap.add(he94);
        globalHandicap.add(he95);
        globalHandicap.add(he96);
        globalHandicap.add(he97);
        globalHandicap.add(he98);
        globalHandicap.add(he99);
        globalHandicap.add(he100);
        globalHandicap.add(he101);
        globalHandicap.add(he102);
        globalHandicap.add(he103);
        globalHandicap.add(he103);
        globalHandicap.add(he104);
        globalHandicap.add(he105);
        globalHandicap.add(he106);
        globalHandicap.add(he107);
        globalHandicap.add(he108);
        globalHandicap.add(he109);
        globalHandicap.add(he110);
        globalHandicap.add(he111);
        globalHandicap.add(he112);
        globalHandicap.add(he113);
        globalHandicap.add(he114);
        globalHandicap.add(he115);
        globalHandicap.add(he116);
        globalHandicap.add(he117);
        globalHandicap.add(he118);
        globalHandicap.add(he119);
        globalHandicap.add(he120);
        globalHandicap.add(he121);
        globalHandicap.add(he122);
        globalHandicap.add(he123);
        globalHandicap.add(he124);
        globalHandicap.add(he125);
        globalHandicap.add(he126);
        globalHandicap.add(he127);
        globalHandicap.add(he128);
        globalHandicap.add(he129);
        globalHandicap.add(he130);
        globalHandicap.add(he131);
        globalHandicap.add(he132);
        globalHandicap.add(he133);
        globalHandicap.add(he134);
        globalHandicap.add(he135);
        globalHandicap.add(he136);
        globalHandicap.add(he137);
        globalHandicap.add(he138);
        globalHandicap.add(he139);
        globalHandicap.add(he140);
        globalHandicap.add(he141);
        globalHandicap.add(he142);
        globalHandicap.add(he143);
        globalHandicap.add(he144);
        globalHandicap.add(he145);
        globalHandicap.add(he146);
        globalHandicap.add(he147);
        globalHandicap.add(he148);
        globalHandicap.add(he149);
        globalHandicap.add(he150);
        globalHandicap.add(he151);
        globalHandicap.add(he152);
        globalHandicap.add(he153);
        globalHandicap.add(he154);
        globalHandicap.add(he155);
        globalHandicap.add(he156);
        globalHandicap.add(he157);
        globalHandicap.add(he158);
        globalHandicap.add(he159);
        globalHandicap.add(he160);
        globalHandicap.add(he161);
        globalHandicap.add(he162);
        globalHandicap.add(he163);
        globalHandicap.add(he164);
        globalHandicap.add(he165);
        globalHandicap.add(he166);
        globalHandicap.add(he167);
        globalHandicap.add(he168);
        globalHandicap.add(he169);
        globalHandicap.add(he170);
        globalHandicap.add(he171);
        globalHandicap.add(he172);
        globalHandicap.add(he173);
        globalHandicap.add(he174);
        globalHandicap.add(he175);
        globalHandicap.add(he176);
        globalHandicap.add(he177);
        globalHandicap.add(he178);
        globalHandicap.add(he179);
        globalHandicap.add(he180);
        globalHandicap.add(he181);
        globalHandicap.add(he182);
        globalHandicap.add(he183);
        globalHandicap.add(he184);
        globalHandicap.add(he185);
        globalHandicap.add(he186);
        globalHandicap.add(he187);
        globalHandicap.add(he188);
        globalHandicap.add(he189);
        globalHandicap.add(he190);
        globalHandicap.add(he191);
        globalHandicap.add(he192);
        globalHandicap.add(he193);
        globalHandicap.add(he194);
        globalHandicap.add(he195);
        globalHandicap.add(he196);
        globalHandicap.add(he197);
        globalHandicap.add(he198);
        globalHandicap.add(he199);
        globalHandicap.add(he200);
        globalHandicap.add(he201);
        globalHandicap.add(he202);
        globalHandicap.add(he203);
        globalHandicap.add(he204);
        globalHandicap.add(he205);
        globalHandicap.add(he206);
        globalHandicap.add(he207);
        globalHandicap.add(he208);


    }

}
